import type { Metadata } from 'next';
import * as fonts from '@/utils/fonts';
import './globals.scss';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      className={`${fonts.lato.variable} ${fonts.absolutely_vintage.variable}`}
      lang="en"
    >
      <body>{children}</body>
    </html>
  );
}
